# Generated by Django 5.2.3 on 2025-06-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_file_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('submitted', 'Подана'), ('under_review', 'На рецензировании'), ('published', 'Опубликована'), ('rejected', 'Отклонена')], default='submitted', max_length=20),
        ),
    ]
