# Generated by Django 5.2.3 on 2025-06-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articlerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
