# Generated by Django 5.2.3 on 2025-07-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_userviewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/pdfs'),
        ),
    ]
