# Generated by Django 5.2.3 on 2025-07-02 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(error_messages={'max_length': 'Заголовок не может превышать 200 символов.', 'min_length': 'Заголовок должен содержать минимум 10 символов.'}, max_length=100, validators=[django.core.validators.RegexValidator(message='Название содержит запрещенные символы.', regex='^[^!@#$%^&*()+={}\\[\\]|\\\\:;"\\\'<>?,~`]+$')]),
        ),
    ]
