# Generated by Django 5.2.3 on 2025-07-02 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(error_messages={'max_length': 'Название не может превышать 50 символов.'}, max_length=50, validators=[django.core.validators.MinLengthValidator(5, message='Название должено содержать минимум 5 символов'), django.core.validators.RegexValidator(message='Название содержит запрещенные символы.', regex='^[^!@#$%^&*()+={}\\[\\]|\\\\:;"\\\'<>?,~`]+$')]),
        ),
    ]
