# Generated by Django 5.2.3 on 2025-07-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required: 150 charters, letters. digits and @/./+/-/_ only.', max_length=30, unique=True),
        ),
    ]
