# Generated by Django 5.2.3 on 2025-07-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required: 4-30 letters, digits and @/./+/-/_ characters.', max_length=30, unique=True),
        ),
    ]
