# Generated by Django 5.2.3 on 2025-07-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='Required: 3-10 letters.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='Required: 3-10 letters.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required: 4-30 letters, digits and @/./+/-/_ characters.', unique=True),
        ),
    ]
