# Generated by Django 5.2.3 on 2025-07-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_alter_article_title_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Required A-z letters, and digits 0-9', unique=True),
        ),
    ]
